# .github/workflows/eject-production.yml
##
# Eject production
#
# Export a Trellis-managed site from production
# for delivery to a traditional WordPress environment
# and attach artifacts to the workflow run for download
##

name: ⏏️ Eject production for delivery
run-name: eject-production

on:
  workflow_dispatch:

env:
  from: production

jobs:
  eject-production:
    runs-on: ubuntu-latest
    steps:

      # Checkout the repo
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      # Eject production for delivery
      - uses: ./.github/actions/eject
        name: Eject production for delivery
        with:
          from: ${{ env.from }}
          trellis_site_slug: ${{ secrets.TRELLIS_SITE_SLUG }}
          trellis_deploy_ssh_private_key: ${{ secrets.TRELLIS_DEPLOY_SSH_PRIVATE_KEY }}
          trellis_deploy_ssh_known_hosts: ${{ secrets.TRELLIS_DEPLOY_SSH_KNOWN_HOSTS }}
          working_directory: ./site
          github_token: ${{ secrets.GITHUB_TOKEN }}
