name: Deploy to production
run-name: Deploy to production

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  deploy:
    if: github.event.pull_request.merged || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/trellis-cli.yml
    secrets: inherit
    with:
      environment: 'production'
