name: Deploy to production
run-name: Deploy to production

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    if: github.repository != 'MWDelaney/trellis-template'
    uses: ./.github/workflows/trellis-cli.yml
    secrets: inherit
