name: 🏷️ Rename the project from template

on: [push]

permissions: write-all

jobs:
  rename-project:
    if: ${{ !contains (github.repository, '/wordress-project-template') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # by default, it uses a depth of 1
          # this fetches all history so that we can read each commit
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}' | tr '-' '_' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
        shell: bash

      - run: echo "REPOSITORY_URLNAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
        shell: bash

      - run: echo "REPOSITORY_OWNER=$(echo '${{ github.repository }}' | awk -F '/' '{print $1}')" >> $GITHUB_ENV
        shell: bash

      - name: Is this still a template
        id: is_template
        run: echo "::set-output name=is_template::$(ls .github/template.yml &> /dev/null && echo true || echo false)"

      - name: Rename the project
        if: steps.is_template.outputs.is_template == 'true'
        run: |
          echo "Renaming the project with -a(author) ${{ env.REPOSITORY_OWNER }} -n(name) ${{ env.REPOSITORY_NAME }} -u(urlname) ${{ env.REPOSITORY_URLNAME }}"
          .github/rename_project.sh -a ${{ env.REPOSITORY_OWNER }} -n ${{ env.REPOSITORY_NAME }} -u ${{ env.REPOSITORY_URLNAME }} -d "New WordPress project ${{ env.REPOSITORY_NAME }} created by ${{ env.REPOSITORY_OWNER }}"

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "✅ Ready to clone and code."
          # commit_options: '--amend --no-edit'
          push_options: --force

  update-readme:
    runs-on: ubuntu-latest
    steps:

      #Checkout the repo
      - uses: actions/checkout@v3

      # Replace repository slug
      - name: Replace repository slug
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "MWDelaney/example.com"
          replace: "${{ github.repository_owner }}/${{ github.event.repository.name }}"
          include: ".github/README.template.md"
          regex: false

      # Replace repository title
      - name: Replace repository title
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "# example.com"
          replace: "# ${{ github.event.repository.name }}"
          include: ".github/README.template.md"
          regex: false

      # Change the filename to .README
      - name: Rename README
        shell: bash
        run: mv .github/README.template.md .github/README.md

      # Commit changes
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "📝 Updated README"
