# `setup-trellis-cli` action for deploying Trellis sites with optional Sage 10-based theme build
##
# Replace `sage` with your theme folder

name: trellis-cli
run-name: 'Trellis CLI'

on:
  workflow_call:
    inputs:
      extra-vars:
        required: false
        type: string
        default: ""

jobs:
  trellis-cli:
    runs-on: ubuntu-latest
    if: github.repository != 'MWDelaney/trellis-template'

    steps:
    - uses: actions/checkout@v2

    # Optional sage build, should be refactored into separate workflow
    # - uses: actions/setup-node@v2
    #   with:
    #     node-version: '16'
    #     cache: yarn
    #     cache-dependency-path: site/web/app/themes/sage/yarn.lock

    - uses: andstor/file-existence-action@v2
      id: check_files
      with:
        files: "trellis/deploy.yml"
    - uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.TRELLIS_DEPLOY_SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.TRELLIS_DEPLOY_SSH_KNOWN_HOSTS }}
    - uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.TRELLIS_DEPLOY_SSH_PRIVATE_KEY }}
    - uses: roots/setup-trellis-cli@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        ansible-vault-password: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
    - name: Deploy
      if: steps.check_files.outputs.files_exists == 'true'
      run: trellis deploy --extra-vars ${{ inputs.extra-vars }} ${{ github.ref_name }}
